# Site wide configuration

title:            Rob Weyant
locale:           en_US
url: http://rweyant.github.io


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Octopress

# Default extensions
post_ext: md
page_ext: md

# Found in _templates/
post_layout: post
page_layout: page

# Format titles with titlecase?
titlecase: true

excerpt_separator: "" 

# Site owner
owner:
  name: Rob Weyant
  avatar: sleeping-bear-dune.jpg
  bio: "Data Scientist at Powerley"
  email:
  disqus-shortname:
  twitter: RobWeyant
  facebook: #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: rweyant
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: robertweyant
  xing: #username
  instagram: rweyant
  lastfm: rweyant
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #photos/133670842@N08
  codepen: #username 
  meetup: rweyant

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
