---
layout: post
title: "gspread - A wrapper for Google Spreadsheets in Python"
categories: [Python]
tags: [Python, API, googledocs ]
excerpt: #
modified: 2016-01-31
comments: true
image:
  feature: current-feature.jpg
---

```{r setup, echo=FALSE, warning=FALSE,cache=FALSE,results='hide'}
source('~/Documents/code/bertplot/R/source/common_rmd_options.R')
```

[**gspread**](https://github.com/burnash/gspread) is a package by [Anton Burnashev](https://github.com/burnash) offers a simple interface between Python and Google Spreadsheet's API.  

## Installation

```{python, eval=FALSE,results='hide'}
# From PyPi
pip install gspread
```

## Authorization

Google Spreadsheet's API uses OAuth2 to handle authorization.  You'll need to generate an [API Key](https://console.developers.google.com/).  You can also use email/password to login with `gspread.login(email,password)`.

```{python, eval=FALSE}
import gspread
import json

oauthfile = '/path/to/file/your-api-key.json',                  
scope = ['https://spreadsheets.google.com/feeds']
json_key = json.load(open(oauthfile))
credentials = SignedJwtAssertionCredentials(json_key['client_email'], json_key['private_key'], scope)

# Authorize
gspreadclient = gspread.authorize(credentials)
```

## Accessing Data

```{python, eval=FALSE}
# Load spreadsheet
spreadsheet = gspreadclient.open('your spreadsheet')

# Load worksheet
worksheet = spreadsheet.worksheet('your worksheet')

# Get all values
dat = worksheet.get_all_values()
```

The `gspread.Worksheet.get_all_values()` returns a list of lists which is easily converted to NumPy format or just indexing normally.  You can also get a specific row with `gspread.Worksheet.row_values()` and a specific cell with `gspread.Worksheet.cell()`.

## Updating Cells

```{python, eval=FALSE}
# Insert 'abc' into the cell at the first row, first column.
worksheet.update_cell(1,1,'abc')
```

There are other functions to update the data, mainly `gspread.Worksheet.append_row()`.  You can also change the size of the worksheet with `gspread.Worksheet.add_rows()`,`gspread.Worksheet.add_cols()`, `gspread.Worksheet.resize()`.


## More Resources
- [Read the Docs](https://gspread.readthedocs.org/en/latest/)
- [Package Source on Github](https://github.com/burnash/gspread)
- [Package on PyPi](https://pypi.python.org/pypi/gspread)
- [Source as RMarkdown](https://github.com/rweyant/bertplot/)
